name: AI Service API Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: string
        run: echo "welcome to Backend"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt
            

      - name: Run linters
        run: |


      - name: Run tests
        run: |
          pip install pytest
          pytest tests.py

